const darwinGamers = {
  ShaunZomGaming: {
    uid: 1,
    name: "Shaun Zom Gaming",
    image: "/images/pfp/szg.jpeg",
    mainclass: "Grapple Gauntlet",
    director: true,
    location: "NA East",
    tourneycount: 2,
    email: "shaunzomgaming@gmail.com",
    discord: "ShaunZomGaming#1597",
    stream: "www.twitch.tv/shaunzomgaming",
    twitter: "shaunzomgaming",
    notes: "Director Main, but does his best at inmate"
  },
  Cole_Story_Bro: {
    uid: 2,
    name: "Cole_Story_Bro",
    director: false,
    image: "/images/pfp/cole.png",
    mainclass: "Headhunter Drone",
    location: "NA East",
    tourneycount: 4,
    email: "colestorybro@gmail.com",
    discord: "Cole_Story_Bro#7341",
    stream: "www.twitch.tv/shaunzomgaming",
    twitter: "shaunzomgaming",
    notes: "He pops off"
  },
  PrimalCinder: {
    uid: 3,
    name: "PrimalCinder",
    image: "/images/pfp/cole.png",
    mainclass: "Jet Wings",
    director: false,
    location: "NA East",
    tourneycount: 5,
    email: "primalcinder@gmail.com",
    discord: "primalcinder#7341",
    stream: "www.twitch.tv/shaunzomgaming",
    twitter: "primalcinder",
    notes: "He pops off"
  },
  PotterSauce: {
    uid: 4,
    name: "PotterSauce",
    image: "/images/pfp/potter.png",
    mainclass: "Headhunter Drone",
    director: true,
    location: "NA West",
    tourneycount: 5,
    email: "pottersauce@gmail.com",
    discord: "pottersauce#7341",
    stream: "www.twitch.tv/pottersauce",
    twitter: "pottersauce",
    notes: "Potter brings the hype"
  },
  MoonShine: {
    uid: 5,
    name: "MoonShine",
    image: "/images/pfp/potter.png",
    mainclass: "Headhunter Drone",
    director: true,
    location: "NA West",
    tourneycount: 5,
    email: "MoonShine@gmail.com",
    discord: "MoonShine#7341",
    stream: "www.twitch.tv/MoonShine",
    twitter: "MoonShine",
    notes: "He is MoonShine"
  },
  SteffKnight: {
    uid: 6,
    name: "SteffKnight",
    image: "/images/pfp/potter.png",
    mainclass: "Headhunter Drone",
    director: true,
    location: "NA West",
    tourneycount: 5,
    email: "SteffKnight@gmail.com",
    discord: "SteffKnight#7341",
    stream: "www.twitch.tv/SteffKnight",
    twitter: "SteffKnight",
    notes: "SteffKnight brings the hype"
  },
  Beniswell: {
    uid: 7,
    name: "Beniswell",
    image: "/images/pfp/potter.png",
    mainclass: "Headhunter Drone",
    director: true,
    location: "NA West",
    tourneycount: 5,
    email: "Beniswell@gmail.com",
    discord: "Beniswell#7341",
    stream: "www.twitch.tv/Beniswell",
    twitter: "Beniswell",
    notes: "Beniswell brings the hype"
  },
  Hayden: {
    uid: 8,
    name: "Hayden",
    image: "/images/pfp/potter.png",
    mainclass: "Headhunter Drone",
    director: true,
    location: "NA West",
    tourneycount: 5,
    email: "Hayden@gmail.com",
    discord: "Hayden#7341",
    stream: "www.twitch.tv/Hayden",
    twitter: "Hayden",
    notes: "Hayden brings the hype"
  },
  PapaMiget: {
    uid: 9,
    name: "PapaMiget",
    image: "/images/pfp/potter.png",
    mainclass: "Headhunter Drone",
    director: true,
    location: "NA West",
    tourneycount: 5,
    email: "PapaMiget@gmail.com",
    discord: "PapaMiget#7341",
    stream: "www.twitch.tv/PapaMiget",
    twitter: "PapaMiget",
    notes: "PapaMiget brings the hype"
  },
  Nutes: {
    uid: 10,
    name: "Nutes",
    image: "/images/pfp/potter.png",
    mainclass: "Headhunter Drone",
    director: true,
    location: "NA West",
    tourneycount: 5,
    email: "Nutes@gmail.com",
    discord: "Nutes#7341",
    stream: "www.twitch.tv/Nutes",
    twitter: "Nutes",
    notes: "Nutes brings the hype"
  },
  Two: {
    uid: 11,
    name: "Two",
    image: "/images/pfp/potter.png",
    mainclass: "Headhunter Drone",
    director: true,
    location: "NA West",
    tourneycount: 5,
    email: "Two@gmail.com",
    discord: "Two#7341",
    stream: "www.twitch.tv/Two",
    twitter: "Two",
    notes: "Two brings the hype"
  },
  Lithium: {
    uid: 12,
    name: "Lithium",
    image: "/images/pfp/potter.png",
    mainclass: "Headhunter Drone",
    director: true,
    location: "NA West",
    tourneycount: 5,
    email: "Lithium@gmail.com",
    discord: "Lithium#7341",
    stream: "www.twitch.tv/Lithium",
    twitter: "Lithium",
    notes: "Lithium brings the hype"
  },
  GoldenSeeker24: {
    uid: 13,
    name: "GoldenSeeker24",
    image: "/images/pfp/potter.png",
    mainclass: "Headhunter Drone",
    director: true,
    location: "NA West",
    tourneycount: 5,
    email: "GoldenSeeker24@gmail.com",
    discord: "GoldenSeeker24#7341",
    stream: "www.twitch.tv/GoldenSeeker24",
    twitter: "GoldenSeeker24",
    notes: "GoldenSeeker24 brings the hype"
  },
  MrDiese: {
    uid: 14,
    name: "MrDiese",
    image: "/images/pfp/potter.png",
    mainclass: "Headhunter Drone",
    director: true,
    location: "NA West",
    tourneycount: 5,
    email: "MrDiese@gmail.com",
    discord: "MrDiese#7341",
    stream: "www.twitch.tv/MrDiese",
    twitter: "MrDiese",
    notes: "MrDiese brings the hype"
  },
  Dexar: {
    uid: 15,
    name: "Dexar",
    image: "/images/pfp/potter.png",
    mainclass: "Headhunter Drone",
    director: true,
    location: "NA West",
    tourneycount: 5,
    email: "Dexar@gmail.com",
    discord: "Dexar#7341",
    stream: "www.twitch.tv/Dexar",
    twitter: "Dexar",
    notes: "Dexar brings the hype"
  },
  Dusta: {
    uid: 16,
    name: "Dusta",
    image: "/images/pfp/potter.png",
    mainclass: "Headhunter Drone",
    director: true,
    location: "NA West",
    tourneycount: 5,
    email: "Dusta@gmail.com",
    discord: "Dusta#7341",
    stream: "www.twitch.tv/Dusta",
    twitter: "Dusta",
    notes: "Dusta brings the hype"
  },
  Jetrvoox: {
    uid: 17,
    name: "Jetrvoox",
    image: "/images/pfp/potter.png",
    mainclass: "Headhunter Drone",
    director: true,
    location: "NA West",
    tourneycount: 5,
    email: "Jetrvoox@gmail.com",
    discord: "Jetrvoox#7341",
    stream: "www.twitch.tv/Jetrvoox",
    twitter: "Jetrvoox",
    notes: "Jetrvoox brings the hype"
  },
  Khyzz: {
    uid: 18,
    name: "Khyzz",
    image: "/images/pfp/potter.png",
    mainclass: "Headhunter Drone",
    director: true,
    location: "NA West",
    tourneycount: 5,
    email: "Khyzz@gmail.com",
    discord: "Khyzz#7341",
    stream: "www.twitch.tv/Khyzz",
    twitter: "Khyzz",
    notes: "Khyzz brings the hype"
  },
  Laykox: {
    uid: 19,
    name: "Laykox",
    image: "/images/pfp/potter.png",
    mainclass: "Headhunter Drone",
    director: true,
    location: "NA West",
    tourneycount: 5,
    email: "Laykox@gmail.com",
    discord: "Laykox#7341",
    stream: "www.twitch.tv/Laykox",
    twitter: "Laykox",
    notes: "Laykox brings the hype"
  },
  Remix: {
    uid: 20,
    name: "Remix",
    image: "/images/pfp/potter.png",
    mainclass: "Headhunter Drone",
    director: true,
    location: "NA West",
    tourneycount: 5,
    email: "Remix@gmail.com",
    discord: "Remix#7341",
    stream: "www.twitch.tv/Remix",
    twitter: "Remix",
    notes: "Remix brings the hype"
  },
  Ross: {
    uid: 21,
    name: "Ross",
    image: "/images/pfp/potter.png",
    mainclass: "Headhunter Drone",
    director: true,
    location: "NA West",
    tourneycount: 5,
    email: "Ross@gmail.com",
    discord: "Ross#7341",
    stream: "www.twitch.tv/Ross",
    twitter: "Ross",
    notes: "Ross brings the hype"
  },
  z3ker: {
    uid: 22,
    name: "z3ker",
    image: "/images/pfp/potter.png",
    mainclass: "Headhunter Drone",
    director: true,
    location: "NA West",
    tourneycount: 5,
    email: "z3ker@gmail.com",
    discord: "z3ker#7341",
    stream: "www.twitch.tv/z3ker",
    twitter: "z3ker",
    notes: "z3ker brings the hype"
  },
  Revolter: {
    uid: 23,
    name: "Revolter",
    image: "/images/pfp/potter.png",
    mainclass: "Headhunter Drone",
    director: true,
    location: "NA West",
    tourneycount: 5,
    email: "Revolter@gmail.com",
    discord: "Revolter#7341",
    stream: "www.twitch.tv/Revolter",
    twitter: "Revolter",
    notes: "Revolter brings the hype"
  },
};

export default darwinGamers;
